[package]
name = "stocker"
version = "0.1.2"
authors = ["Teoh Han Hui <teohhanhui@gmail.com>"]
edition = "2018"
description = "Stocks dashboard"
readme = "README.md"
repository = "https://github.com/teohhanhui/stocker"
license = "MIT OR Apache-2.0"
keywords = ["finance", "stocks", "dashboard"]
categories = ["command-line-utilities", "visualization"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.31"
argh = "0.1.3"
async-std = { version = "1.6.0", features = [ "unstable" ] }
better-panic = "0.2.0"
chrono = "0.4.11"
crossterm = { version = "0.17.5", features = ["event-stream"] }
derive_more = "0.99.7"
im = "15.0.0"
itertools = "0.9.0"
itertools-num = "0.1.3"
libmath = "0.2.1"
parking_lot = "0.10.2"
reactive-rs = "0.1.1"
shrinkwraprs = "0.3.0"
smol = { version = "0.1.11", features = ["tokio02"] }
smol-potat = "0.3.3"
strum = "0.18.0"
strum_macros = "0.18.0"
ta = "0.1.5"
thiserror = "1.0.19"
tui = { version = "0.9.5", default-features = false, features = ['crossterm'] }
yahoo-finance = "0.3.0"

[patch.crates-io]
tui = { git = "https://github.com/fdehau/tui-rs" }
yahoo-finance = { git = "https://github.com/fbriden/yahoo-finance-rs" }
